name: Deploy docs
on:
  push:
    branches: [main]
    paths:
      - 'Documentation/R-Type/**'

jobs:
  deploy:
    if: github.repository != 'EpitechPGE3-2026/G-ING-500-LIL-5-1-rtype-4'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Documentation/R-Type
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g vercel
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}